# Generated by Django 5.0 on 2025-11-12 15:46

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myself',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='A picture of yourself', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='myself',
            name='image_demo',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='One of your favorite professional picture', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='myself',
            name='image_tool',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='A picture of your camera or phone you use to take pictures', max_length=255, null=True),
        ),
    ]
