# Generated by Django 5.0 on 2025-11-12 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phot', '0002_alter_myself_image_alter_myself_image_demo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='Featured',
            new_name='featured',
        ),
    ]
