# Generated by Django 5.0 on 2025-11-12 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phot', '0003_rename_featured_photo_featured'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='caption',
            new_name='description',
        ),
        migrations.AddField(
            model_name='photo',
            name='title',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
