# Generated by Django 5.0 on 2025-11-17 16:03

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phot', '0005_bookings_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='full_name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='myself',
            name='expertise',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='myself',
            name='image',
            field=cloudinary.models.CloudinaryField(help_text='A picture of yourself', max_length=255),
        ),
        migrations.AlterField(
            model_name='myself',
            name='image_demo',
            field=cloudinary.models.CloudinaryField(help_text='One of your favorite professional picture', max_length=255),
        ),
        migrations.AlterField(
            model_name='myself',
            name='image_tool',
            field=cloudinary.models.CloudinaryField(help_text='A picture of your camera or phone you use to take pictures', max_length=255),
        ),
        migrations.AlterField(
            model_name='myself',
            name='my_story',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='myself',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='photo',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
        migrations.AlterField(
            model_name='photo',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='photo',
            name='title',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='service_photo',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='service_photo',
            name='description',
            field=models.TextField(help_text='list of photos youll take and edit for the client'),
        ),
        migrations.AlterField(
            model_name='service_photo',
            name='name',
            field=models.CharField(),
        ),
    ]
