# Generated by Django 5.0 on 2025-12-11 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phot', '0006_alter_bookings_full_name_alter_myself_expertise_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteVisitertgerg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('referrer', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
