# Generated by Django 5.0 on 2026-04-16 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phot', '0007_websitevisitertgerg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='slug',
            field=models.SlugField(max_length=500),
        ),
        migrations.AlterField(
            model_name='photo',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
