# Generated by Django 5.2.7 on 2025-11-04 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='api_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='api_secret',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='cloud_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='flutterwave_subaccount_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
