# Generated by Django 5.2.7 on 2025-11-04 17:14

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b_manager', '0002_client_api_key_client_api_secret_client_cloud_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='logo',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='logo/'),
        ),
    ]
