# Generated by Django 5.2.7 on 2025-11-04 19:55

import b_manager.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b_manager', '0005_alter_client_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='business_picture',
            field=models.ImageField(blank=True, null=True, upload_to=b_manager.models.business_picture_upload_to),
        ),
        migrations.AlterField(
            model_name='client',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=b_manager.models.logo_upload_to),
        ),
    ]
