# Generated by Django 5.0 on 2025-11-05 08:32

import django.db.models.deletion
import secrets
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b_manager', '0006_alter_client_business_picture_alter_client_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantAPIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(default=secrets.token_urlsafe, max_length=128, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='b_manager.client')),
            ],
        ),
    ]
