# Generated by Django 5.0 on 2025-11-06 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b_manager', '0009_alter_client_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
