# Generated by Django 5.0 on 2025-11-12 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b_manager', '0010_alter_client_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitetemplate',
            name='category',
            field=models.CharField(blank=True, choices=[('Store', 'Store '), ('Restaurant', 'Restaurant'), ('Freelancer', 'Portfolio and Freelancer'), ('Photo Artist', 'Photo Artist'), ('Influencers', 'Content creator and Marketers '), ('Company', 'Company'), ('Blogger', '\tBlog'), ('Food Vendor', 'Food Vendor')], max_length=100, null=True),
        ),
    ]
