# Generated by Django 5.0 on 2025-11-13 11:07

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b_manager', '0011_alter_websitetemplate_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitetemplate',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='template_thumbnails/'),
        ),
    ]
