# Generated by Django 5.0 on 2025-11-22 13:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b_manager', '0013_tut_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='b_manager.client'),
        ),
    ]
