# Generated by Django 5.0 on 2025-11-23 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b_manager', '0015_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='grace_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
