# Generated by Django 5.0 on 2025-11-23 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b_manager', '0016_client_grace_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='auto_renew',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='client',
            name='paystack_customer_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='paystack_email_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='paystack_subscription_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
