# Generated by Django 5.0 on 2025-11-23 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b_manager', '0017_client_auto_renew_client_paystack_customer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
