# Generated by Django 5.0 on 2025-11-24 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('b_manager', '0018_alter_subscriptionplan_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='grace_until',
        ),
    ]
