# Generated by Django 5.0 on 2025-11-25 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b_manager', '0019_remove_client_grace_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='free',
            field=models.BooleanField(default=False),
        ),
    ]
