# Generated by Django 5.0 on 2025-11-26 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b_manager', '0020_client_free'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='flutterwave_payment_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='flutterwave_split_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
