# Generated by Django 5.0 on 2025-11-27 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b_manager', '0022_websitevisit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitevisit',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='b_manager.client'),
        ),
    ]
