# Generated by Django 5.0 on 2025-11-27 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b_manager', '0023_alter_websitevisit_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitevisit',
            name='referrer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
