# Generated by Django 5.0 on 2025-12-09 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b_manager', '0024_websitevisit_referrer'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='min_plan',
            field=models.CharField(blank=True, choices=[('free', 'Free Plan'), ('basic', 'Basic Plan'), ('premium', 'Premium Plan')], default='free', help_text='Minimum subscription plan required to use this template.', max_length=20, null=True),
        ),
    ]
