# Generated by Django 5.0 on 2025-12-10 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b_manager', '0025_job_min_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='facebook',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='instagram',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='linkedin',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='tiktok',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
