# Generated by Django 5.0 on 2025-12-10 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b_manager', '0026_client_facebook_client_instagram_client_linkedin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='business_logistics',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='business_working_hours',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
