# Generated by Django 5.0 on 2025-12-20 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b_manager', '0027_client_business_logistics_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=True, max_length=255)),
                ('video', models.URLField()),
            ],
        ),
    ]
