# Generated by Django 5.2.7 on 2025-10-23 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_remove_product_name_remove_product_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='best_sellers',
            field=models.BooleanField(default=False),
        ),
    ]
