# Generated by Django 5.2.7 on 2025-10-23 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0009_color_remove_product_quantity_remove_product_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='color',
        ),
        migrations.DeleteModel(
            name='Color',
        ),
    ]
