# Generated by Django 5.2.7 on 2025-10-24 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0011_cart_session_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
