# Generated by Django 5.2.7 on 2025-10-24 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0012_remove_product_price_productvariant_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='price',
            field=models.FloatField(default=100),
        ),
    ]
