# Generated by Django 5.2.7 on 2025-10-24 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0016_address_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
