# Generated by Django 5.2.7 on 2025-10-25 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0020_order_email_order_ordered_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cart',
            field=models.ManyToManyField(to='ecommerce.cart'),
        ),
    ]
