# Generated by Django 5.2.7 on 2025-10-26 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0022_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='discount_price',
            field=models.FloatField(default=80),
        ),
    ]
