# Generated by Django 5.2.7 on 2025-10-26 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0023_productvariant_discount_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='discount_price',
            field=models.FloatField(),
        ),
    ]
