# Generated by Django 5.2.7 on 2025-10-31 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('delivery_fee', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('has_local_government', models.BooleanField(default=False, help_text='If true, use city-level pricing for this state.')),
                ('fixed_price', models.FloatField(blank=True, help_text='Flat delivery price for states without LGAs.', null=True)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_fee',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_option',
            field=models.CharField(blank=True, choices=[('pickup', 'Pick up from store (₦0)'), ('door', 'Deliver to my address')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='pick',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecom.deliverycity'),
        ),
        migrations.AddField(
            model_name='deliverycity',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='ecom.deliverystate'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecom.deliverystate'),
        ),
        migrations.AlterUniqueTogether(
            name='deliverycity',
            unique_together={('state', 'name')},
        ),
    ]
