# Generated by Django 5.2.7 on 2025-11-01 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0002_deliverycity_deliverystate_order_delivery_fee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_city',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_state',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pick',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='pick it up at the store'),
        ),
    ]
