# Generated by Django 5.2.7 on 2025-11-01 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0003_remove_order_delivery_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_option',
        ),
    ]
