# Generated by Django 5.2.7 on 2025-11-04 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0004_remove_order_delivery_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverystate',
            name='fixed_price',
            field=models.FloatField(blank=True, help_text='put only figures eg(50000).', null=True),
        ),
    ]
