# Generated by Django 5.0 on 2025-11-15 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0007_sale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='product',
        ),
        migrations.AddField(
            model_name='sale',
            name='product',
            field=models.ManyToManyField(blank=True, null=True, to='ecom.product'),
        ),
    ]
