# Generated by Django 5.0 on 2025-11-15 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0012_alter_product_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='reference',
            field=models.CharField(default='hjsgfjhvrr23', max_length=100),
        ),
    ]
