# Generated by Django 5.0 on 2025-11-15 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0013_sale_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='reference',
            field=models.CharField(max_length=100),
        ),
    ]
