# Generated by Django 5.0 on 2025-11-15 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0017_alter_sale_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='reference',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
