# Generated by Django 5.0 on 2025-11-15 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0018_alter_sale_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='quantity_sold',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
