# Generated by Django 5.0 on 2025-11-17 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0021_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='ecom/'),
        ),
    ]
