# Generated by Django 5.0 on 2025-11-19 16:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0024_alter_product_name_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='amount',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='sale',
            name='cost',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
