# Generated by Django 5.0 on 2025-11-19 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0025_sale_amount_sale_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deliv',
            field=models.BooleanField(default=False),
        ),
    ]
