# Generated by Django 5.0 on 2025-11-19 21:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0026_order_deliv'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cost',
            field=models.FloatField(default=500, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='sale',
            name='cost',
            field=models.FloatField(blank=True, default=500, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
