# Generated by Django 5.0 on 2025-11-19 22:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0027_product_cost_alter_sale_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='amount',
            field=models.FloatField(help_text='The amount you sold the product', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='sale',
            name='cost',
            field=models.FloatField(help_text='The total amount you paid to get the product', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total',
            field=models.FloatField(help_text='The profit you made'),
        ),
    ]
