# Generated by Django 5.0 on 2025-11-26 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0028_alter_sale_amount_alter_sale_cost_alter_sale_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(blank=True, default='Nigeria', max_length=100, null=True),
        ),
    ]
