# Generated by Django 5.0 on 2025-11-26 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0029_alter_address_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
