# Generated by Django 5.0 on 2026-01-19 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0033_websitevisitgrtghbr'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='delivery_feeeeee',
            field=models.FloatField(default=0.0),
        ),
    ]
