# Generated by Django 5.0 on 2026-04-07 14:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0034_sale_delivery_feeeeee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cost',
            field=models.FloatField(default=0, help_text='The total cost you spent to get the product', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
