# Generated by Django 5.0 on 2025-11-28 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_thumbnail_alter_blog_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='tags',
            new_name='cataegory',
        ),
    ]
