# Generated by Django 5.0 on 2025-11-28 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blog_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='comment',
        ),
        migrations.AddField(
            model_name='blog',
            name='comment',
            field=models.ManyToManyField(blank=True, to='blog.comm'),
        ),
    ]
