# Generated by Django 5.0 on 2025-11-28 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_blog_comment_blog_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='msg',
            old_name='messsage',
            new_name='message',
        ),
    ]
