# Generated by Django 5.0 on 2025-11-29 00:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_sub'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sub',
            options={'ordering': ['-subscribed_at'], 'verbose_name': 'Subscriber', 'verbose_name_plural': 'Subscribers'},
        ),
        migrations.AddField(
            model_name='sub',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sub',
            name='subscribed_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sub',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
