# Generated by Django 5.0 on 2025-12-07 17:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_sub_options_sub_is_active_sub_subscribed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='msg',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
