# Generated by Django 5.0 on 2026-04-16 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_websiteviwreger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='cataegory',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='msg',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
