# Generated by Django 5.0 on 2025-12-08 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_alter_menu_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Booking',
            new_name='Bookdbdbd',
        ),
    ]
