# Generated by Django 5.0 on 2025-12-08 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_rename_booking_bookdbdbd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catgg',
            name='name',
            field=models.CharField(choices=[('appetizers', 'Appetizers'), ('main_courses', 'Main Courses'), ('desserts', 'Desserts'), ('cocktails', 'Cocktails'), ('mocktails', 'Mocktails'), ('sides', 'Sides'), ('beverages', 'Non-Alcoholic Beverages'), ('wine_beer', 'Wine & Beer')], max_length=100),
        ),
    ]
