# Generated by Django 5.0 on 2026-04-16 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_alter_catgg_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catgg',
            name='name',
            field=models.CharField(choices=[('appetizers', 'Appetizers'), ('main_courses', 'Main Courses'), ('desserts', 'Desserts'), ('cocktails', 'Cocktails'), ('mocktails', 'Mocktails'), ('sides', 'Sides'), ('beverages', 'Non-Alcoholic Beverages'), ('wine_beer', 'Wine & Beer')], max_length=250),
        ),
        migrations.AlterField(
            model_name='catgg',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, unique=True),
        ),
    ]
