# Generated by Django 5.0 on 2025-11-29 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serv',
            name='premuim',
            field=models.BooleanField(default=False),
        ),
    ]
