# Generated by Django 5.0 on 2025-11-29 19:40

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_serv_premuim'),
    ]

    operations = [
        migrations.AddField(
            model_name='abut',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
