# Generated by Django 5.0 on 2025-12-06 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_alter_imes_options_imes_created_at_alter_imes_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serv',
            old_name='premuim',
            new_name='premium',
        ),
    ]
