# Generated by Django 5.0 on 2025-12-06 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_rename_premuim_serv_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='abut',
            name='title',
            field=models.CharField(default='About Company'),
        ),
    ]
