# Generated by Django 5.0 on 2025-11-06 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_alter_about_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mess',
            old_name='Messages',
            new_name='messages',
        ),
    ]
