# Generated by Django 5.0 on 2025-11-06 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_rename_messages_mess_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campagin',
            name='Problem',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='campagin',
            name='Title',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='campagin',
            name='solution',
            field=models.TextField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='socails',
            name='like',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='socails',
            name='name',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='socails',
            name='social_media',
            field=models.CharField(blank=True),
        ),
    ]
