# Generated by Django 5.0 on 2025-11-06 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_alter_campagin_problem_alter_campagin_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='title',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='title',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='mess',
            name='name',
            field=models.CharField(blank=True),
        ),
    ]
