# Generated by Django 5.0 on 2025-11-06 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_alter_about_title_alter_home_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socails',
            name='views',
            field=models.CharField(blank=True),
        ),
    ]
