# Generated by Django 5.0 on 2025-11-06 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_socails_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='socails',
            name='social_media',
        ),
        migrations.AddField(
            model_name='socails',
            name='category',
            field=models.ManyToManyField(to='content.category'),
        ),
    ]
