# Generated by Django 5.0 on 2025-11-06 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_category_remove_socails_social_media_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='title',
            new_name='name',
        ),
    ]
