# Generated by Django 5.0 on 2025-11-06 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_rename_title_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='socails',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='tunb/'),
        ),
    ]
