# Generated by Django 5.0 on 2025-11-06 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_socails_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socails',
            name='like',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='socails',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='socails',
            name='views',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
