# Generated by Django 5.0 on 2025-11-06 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_alter_socails_like_alter_socails_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socails',
            name='like',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='socails',
            name='name',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='socails',
            name='views',
            field=models.CharField(blank=True),
        ),
    ]
