# Generated by Django 5.0 on 2025-11-07 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_alter_socails_like_alter_socails_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campagin',
            name='solution',
            field=models.TextField(blank=True),
        ),
    ]
