# Generated by Django 5.0 on 2025-11-07 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0017_rename_problem_campagin_problem_campagin_result_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campagin',
            name='overview',
            field=models.TextField(blank=True, max_length=150),
        ),
    ]
