# Generated by Django 5.0 on 2025-11-07 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0018_campagin_overview'),
    ]

    operations = [
        migrations.AddField(
            model_name='socails',
            name='comment',
            field=models.CharField(blank=True),
        ),
    ]
