# Generated by Django 5.0 on 2025-11-07 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0019_socails_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, help_text='list what will post either one video or multiple video and the socail media'),
        ),
    ]
