# Generated by Django 5.0 on 2025-11-07 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0020_alter_service_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socails',
            name='category',
        ),
        migrations.AddField(
            model_name='socails',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.category'),
        ),
    ]
