# Generated by Django 5.0 on 2025-11-07 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0021_remove_socails_category_socails_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Categorysss',
        ),
    ]
