# Generated by Django 5.0 on 2025-11-08 09:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0022_rename_category_categorysss'),
    ]

    operations = [
        migrations.AddField(
            model_name='mess',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
