# Generated by Django 5.0 on 2025-11-15 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0024_alter_about_image_alter_home_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socails',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.categorysss'),
        ),
    ]
