# Generated by Django 5.0 on 2025-11-17 16:03

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0025_alter_socails_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='about',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
        migrations.AlterField(
            model_name='about',
            name='title',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='campagin',
            name='Title',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='campagin',
            name='overview',
            field=models.TextField(help_text='share the overview of what you did'),
        ),
        migrations.AlterField(
            model_name='campagin',
            name='problem',
            field=models.TextField(help_text='explain the problems the clients faced'),
        ),
        migrations.AlterField(
            model_name='campagin',
            name='result',
            field=models.TextField(help_text='Share the result'),
        ),
        migrations.AlterField(
            model_name='campagin',
            name='social',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.socails'),
        ),
        migrations.AlterField(
            model_name='campagin',
            name='solution',
            field=models.TextField(help_text='Share the solutions that you took'),
        ),
        migrations.AlterField(
            model_name='home',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='home',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
        migrations.AlterField(
            model_name='home',
            name='title',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='mess',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='mess',
            name='name',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='service',
            name='amount',
            field=models.FloatField(help_text=" the amount you'll charge"),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(help_text="list of what will you post either one video or multiple video and the socail media you'll post it"),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='socails',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.categorysss'),
        ),
        migrations.AlterField(
            model_name='socails',
            name='link',
            field=models.URLField(help_text='paste the link of the video'),
        ),
        migrations.AlterField(
            model_name='socails',
            name='name',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='socails',
            name='thumbnail',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
