# Generated by Django 5.0 on 2026-04-16 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0027_websitevisiterggssfe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorysss',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='categorysss',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, unique=True),
        ),
    ]
